use super::*;

const NSGLOBAL: &str = "NSGlobalDomain";
const MULTITOUCH_MOUSE: &str = "com.apple.AppleMultitouchMouse";
const BT_MOUSE: &str = "com.apple.driver.AppleBluetoothMultitouch.mouse";
const MULTITOUCH_TRACKPAD: &str = "com.apple.AppleMultitouchTrackpad";
const BT_TRACKPAD: &str = "com.apple.driver.AppleBluetoothMultitouch.trackpad";
const UNIVERSAL_ACCESS: &str = "com.apple.universalaccess";

fn float_range(min: f64, max: f64, step: f64) -> Constraint {
    Constraint::FloatRange(FloatRange { min, max, step })
}

fn int_range(min: i64, max: i64) -> Constraint {
    Constraint::IntRange(IntRange { min, max })
}

pub fn all_settings() -> Vec<SettingDef> {
    vec![
        // ── Group 1: Mouse (NSGlobalDomain) ──
        SettingDef {
            id: "mouse_tracking_speed",
            domain: NSGLOBAL,
            key: "com.apple.mouse.scaling",
            value_type: ValueType::Float,
            constraint: float_range(-1.0, 11.0, 0.25),
            description: "Tracking speed",
            group: SettingGroup::Mouse,
            mirror_domains: &[],
            requires_logout: false,
            help: "How fast the cursor moves. Higher = faster",
        },
        SettingDef {
            id: "mouse_linear",
            domain: NSGLOBAL,
            key: "com.apple.mouse.linear",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Disable acceleration",
            group: SettingGroup::Mouse,
            mirror_domains: &[],
            requires_logout: false,
            help: "Uses constant speed instead of acceleration curve",
        },
        SettingDef {
            id: "scroll_wheel_speed",
            domain: NSGLOBAL,
            key: "com.apple.scrollwheel.scaling",
            value_type: ValueType::Float,
            constraint: float_range(-1.0, 11.0, 0.25),
            description: "Scroll wheel speed",
            group: SettingGroup::Mouse,
            mirror_domains: &[],
            requires_logout: false,
            help: "How fast the scroll wheel scrolls. Higher = faster",
        },
        SettingDef {
            id: "natural_scroll",
            domain: NSGLOBAL,
            key: "com.apple.swipescrolldirection",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Natural scroll direction",
            group: SettingGroup::Mouse,
            mirror_domains: &[],
            requires_logout: true,
            help: "Content moves with finger direction, like a touchscreen",
        },
        SettingDef {
            id: "mouse_swipe_nav",
            domain: NSGLOBAL,
            key: "AppleEnableMouseSwipeNavigateWithScrolls",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Swipe navigation with scrolls",
            group: SettingGroup::Mouse,
            mirror_domains: &[],
            requires_logout: false,
            help: "Swipe left/right to go back/forward in apps",
        },
        SettingDef {
            id: "mouse_double_click_threshold",
            domain: NSGLOBAL,
            key: "com.apple.mouse.doubleClickThreshold",
            value_type: ValueType::Float,
            constraint: float_range(0.0, 3.0, 0.1),
            description: "Double-click threshold (seconds)",
            group: SettingGroup::Mouse,
            mirror_domains: &[],
            requires_logout: false,
            help: "Max time between clicks for a double-click. Higher = more forgiving",
        },
        // ── Group 2: Mouse Hardware ──
        SettingDef {
            id: "mouse_button_mode",
            domain: MULTITOUCH_MOUSE,
            key: "MouseButtonMode",
            value_type: ValueType::Str,
            constraint: Constraint::StringOptions(vec!["OneButton", "TwoButton"]),
            description: "Button mode",
            group: SettingGroup::MouseHardware,
            mirror_domains: &[BT_MOUSE],
            requires_logout: false,
            help: "OneButton = single click, TwoButton = left/right click",
        },
        SettingDef {
            id: "mouse_button_division",
            domain: MULTITOUCH_MOUSE,
            key: "MouseButtonDivision",
            value_type: ValueType::Int,
            constraint: int_range(0, 100),
            description: "Button division (L/R split)",
            group: SettingGroup::MouseHardware,
            mirror_domains: &[BT_MOUSE],
            requires_logout: false,
            help: "Where left/right click zones split. Higher = more right-click area",
        },
        SettingDef {
            id: "mouse_horizontal_scroll",
            domain: MULTITOUCH_MOUSE,
            key: "MouseHorizontalScroll",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Horizontal scroll",
            group: SettingGroup::MouseHardware,
            mirror_domains: &[BT_MOUSE],
            requires_logout: false,
            help: "Allow side-to-side scrolling",
        },
        SettingDef {
            id: "mouse_vertical_scroll",
            domain: MULTITOUCH_MOUSE,
            key: "MouseVerticalScroll",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Vertical scroll",
            group: SettingGroup::MouseHardware,
            mirror_domains: &[BT_MOUSE],
            requires_logout: false,
            help: "Allow up/down scrolling",
        },
        SettingDef {
            id: "mouse_momentum_scroll",
            domain: MULTITOUCH_MOUSE,
            key: "MouseMomentumScroll",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Momentum scroll",
            group: SettingGroup::MouseHardware,
            mirror_domains: &[BT_MOUSE],
            requires_logout: false,
            help: "Scroll continues after lifting finger",
        },
        SettingDef {
            id: "mouse_one_finger_double_tap",
            domain: MULTITOUCH_MOUSE,
            key: "MouseOneFingerDoubleTapGesture",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "One-finger double-tap",
            group: SettingGroup::MouseHardware,
            mirror_domains: &[BT_MOUSE],
            requires_logout: false,
            help: "0=off, 1=smart zoom",
        },
        SettingDef {
            id: "mouse_two_finger_double_tap",
            domain: MULTITOUCH_MOUSE,
            key: "MouseTwoFingerDoubleTapGesture",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "Two-finger double-tap (smart zoom)",
            group: SettingGroup::MouseHardware,
            mirror_domains: &[BT_MOUSE],
            requires_logout: false,
            help: "0=off, 1=smart zoom",
        },
        SettingDef {
            id: "mouse_two_finger_swipe",
            domain: MULTITOUCH_MOUSE,
            key: "MouseTwoFingerHorizSwipeGesture",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "Two-finger swipe between pages",
            group: SettingGroup::MouseHardware,
            mirror_domains: &[BT_MOUSE],
            requires_logout: false,
            help: "0=off, 1=swipe pages, 2=swipe full-screen apps",
        },
        // ── Group 3: Trackpad (NSGlobalDomain) ──
        SettingDef {
            id: "trackpad_tracking_speed",
            domain: NSGLOBAL,
            key: "com.apple.trackpad.scaling",
            value_type: ValueType::Float,
            constraint: float_range(-1.0, 11.0, 0.25),
            description: "Tracking speed",
            group: SettingGroup::Trackpad,
            mirror_domains: &[],
            requires_logout: false,
            help: "How fast the cursor moves. Higher = faster",
        },
        SettingDef {
            id: "trackpad_force_click",
            domain: NSGLOBAL,
            key: "com.apple.trackpad.forceClick",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Force click & haptic feedback",
            group: SettingGroup::Trackpad,
            mirror_domains: &[],
            requires_logout: false,
            help: "Hard press triggers Force Click and haptic response",
        },
        SettingDef {
            id: "trackpad_secondary_click",
            domain: NSGLOBAL,
            key: "com.apple.trackpad.enableSecondaryClick",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Secondary click",
            group: SettingGroup::Trackpad,
            mirror_domains: &[],
            requires_logout: false,
            help: "Two-finger click acts as right-click",
        },
        SettingDef {
            id: "trackpad_corner_click",
            domain: NSGLOBAL,
            key: "com.apple.trackpad.trackpadCornerClickBehavior",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "Corner click behavior",
            group: SettingGroup::Trackpad,
            mirror_domains: &[],
            requires_logout: false,
            help: "0=off, 1=secondary click",
        },
        SettingDef {
            id: "tap_to_click",
            domain: NSGLOBAL,
            key: "com.apple.mouse.tapBehavior",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "Tap to click",
            group: SettingGroup::Trackpad,
            mirror_domains: &[],
            requires_logout: true,
            help: "0=off, 1=tap to click",
        },
        SettingDef {
            id: "trackpad_swipe_nav",
            domain: NSGLOBAL,
            key: "AppleEnableSwipeNavigateWithScrolls",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Swipe navigation with scrolls",
            group: SettingGroup::Trackpad,
            mirror_domains: &[],
            requires_logout: false,
            help: "Swipe left/right to go back/forward in apps",
        },
        // ── Group 4: Trackpad Hardware ──
        SettingDef {
            id: "tp_clicking",
            domain: MULTITOUCH_TRACKPAD,
            key: "Clicking",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Tap to click",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "Light tap registers as a click",
        },
        SettingDef {
            id: "tp_dragging",
            domain: MULTITOUCH_TRACKPAD,
            key: "Dragging",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Tap and drag",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "Double-tap and hold to drag items",
        },
        SettingDef {
            id: "tp_drag_lock",
            domain: MULTITOUCH_TRACKPAD,
            key: "DragLock",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Drag lock",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "Drag doesn't end when finger lifts briefly",
        },
        SettingDef {
            id: "tp_three_finger_drag",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadThreeFingerDrag",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Three-finger drag",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "Use three fingers to drag items",
        },
        SettingDef {
            id: "tp_right_click",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadRightClick",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Two-finger right-click",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "Two-finger click acts as right-click",
        },
        SettingDef {
            id: "tp_corner_secondary",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadCornerSecondaryClick",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "Corner secondary click",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "0=off, 1=bottom-left corner, 2=bottom-right corner",
        },
        SettingDef {
            id: "tp_scroll",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadScroll",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Vertical scroll",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "Two-finger swipe scrolls vertically",
        },
        SettingDef {
            id: "tp_horiz_scroll",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadHorizScroll",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Horizontal scroll",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "Two-finger swipe scrolls horizontally",
        },
        SettingDef {
            id: "tp_momentum_scroll",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadMomentumScroll",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Momentum scrolling",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "Scroll continues after lifting fingers",
        },
        SettingDef {
            id: "tp_pinch",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadPinch",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Pinch to zoom",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "Pinch two fingers to zoom in/out",
        },
        SettingDef {
            id: "tp_rotate",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadRotate",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Two-finger rotate",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "Rotate two fingers to rotate content",
        },
        SettingDef {
            id: "tp_three_finger_tap",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadThreeFingerTapGesture",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "Three-finger tap action",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "0=off, 2=look up & data detectors",
        },
        SettingDef {
            id: "tp_two_finger_double_tap",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadTwoFingerDoubleTapGesture",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "Two-finger double-tap",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "0=off, 1=smart zoom",
        },
        SettingDef {
            id: "tp_right_edge_swipe",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadTwoFingerFromRightEdgeSwipeGesture",
            value_type: ValueType::Int,
            constraint: int_range(0, 3),
            description: "Right-edge swipe",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "0=off, 3=Notification Center",
        },
        SettingDef {
            id: "tp_three_finger_horiz_swipe",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadThreeFingerHorizSwipeGesture",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "Three-finger horizontal swipe",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "0=off, 1=switch pages, 2=switch spaces",
        },
        SettingDef {
            id: "tp_three_finger_vert_swipe",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadThreeFingerVertSwipeGesture",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "Three-finger vertical swipe",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "0=off, 2=Mission Control / App Expose",
        },
        SettingDef {
            id: "tp_four_finger_horiz_swipe",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadFourFingerHorizSwipeGesture",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "Four-finger horizontal swipe",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "0=off, 2=switch spaces",
        },
        SettingDef {
            id: "tp_four_finger_vert_swipe",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadFourFingerVertSwipeGesture",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "Four-finger vertical swipe",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "0=off, 2=Mission Control / App Expose",
        },
        SettingDef {
            id: "tp_four_finger_pinch",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadFourFingerPinchGesture",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "Four-finger pinch",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "0=off, 2=Launchpad",
        },
        SettingDef {
            id: "tp_five_finger_pinch",
            domain: MULTITOUCH_TRACKPAD,
            key: "TrackpadFiveFingerPinchGesture",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "Five-finger pinch",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "0=off, 2=Launchpad",
        },
        SettingDef {
            id: "tp_first_click_threshold",
            domain: MULTITOUCH_TRACKPAD,
            key: "FirstClickThreshold",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "First click pressure",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "0=light, 1=medium, 2=firm",
        },
        SettingDef {
            id: "tp_second_click_threshold",
            domain: MULTITOUCH_TRACKPAD,
            key: "SecondClickThreshold",
            value_type: ValueType::Int,
            constraint: int_range(0, 2),
            description: "Second click pressure",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "0=light, 1=medium, 2=firm",
        },
        SettingDef {
            id: "tp_actuate_detents",
            domain: MULTITOUCH_TRACKPAD,
            key: "ActuateDetents",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Haptic feedback",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "Vibration feedback on trackpad clicks",
        },
        SettingDef {
            id: "tp_force_suppressed",
            domain: MULTITOUCH_TRACKPAD,
            key: "ForceSuppressed",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Suppress force click",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "Disables force click entirely",
        },
        SettingDef {
            id: "tp_usb_mouse_stops",
            domain: MULTITOUCH_TRACKPAD,
            key: "USBMouseStopsTrackpad",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Disable when USB mouse connected",
            group: SettingGroup::TrackpadHardware,
            mirror_domains: &[BT_TRACKPAD],
            requires_logout: false,
            help: "Trackpad turns off when a USB mouse is plugged in",
        },
        // ── Group 5: Scroll & Window Behavior ──
        SettingDef {
            id: "show_scroll_bars",
            domain: NSGLOBAL,
            key: "AppleShowScrollBars",
            value_type: ValueType::Str,
            constraint: Constraint::StringOptions(vec!["WhenScrolling", "Automatic", "Always"]),
            description: "Scrollbar visibility",
            group: SettingGroup::ScrollWindow,
            mirror_domains: &[],
            requires_logout: false,
            help: "When scrollbars appear in windows",
        },
        SettingDef {
            id: "scroller_paging",
            domain: NSGLOBAL,
            key: "AppleScrollerPagingBehavior",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Click scrollbar to jump to spot",
            group: SettingGroup::ScrollWindow,
            mirror_domains: &[],
            requires_logout: false,
            help: "On: jump to clicked spot. Off: scroll one page",
        },
        SettingDef {
            id: "smooth_scrolling",
            domain: NSGLOBAL,
            key: "NSScrollAnimationEnabled",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Smooth scrolling",
            group: SettingGroup::ScrollWindow,
            mirror_domains: &[],
            requires_logout: false,
            help: "Animate scrolling instead of jumping",
        },
        SettingDef {
            id: "double_click_titlebar",
            domain: NSGLOBAL,
            key: "AppleMiniaturizeOnDoubleClick",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Double-click title bar to minimize",
            group: SettingGroup::ScrollWindow,
            mirror_domains: &[],
            requires_logout: false,
            help: "Double-click window title bar to minimize it",
        },
        SettingDef {
            id: "drag_on_gesture",
            domain: NSGLOBAL,
            key: "NSWindowShouldDragOnGesture",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Ctrl+Cmd drag window anywhere",
            group: SettingGroup::ScrollWindow,
            mirror_domains: &[],
            requires_logout: false,
            help: "Hold Ctrl+Cmd and drag anywhere in a window to move it",
        },
        SettingDef {
            id: "springing_enabled",
            domain: NSGLOBAL,
            key: "com.apple.springing.enabled",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Spring-loaded folders",
            group: SettingGroup::ScrollWindow,
            mirror_domains: &[],
            requires_logout: false,
            help: "Hovering over a folder while dragging opens it",
        },
        SettingDef {
            id: "springing_delay",
            domain: NSGLOBAL,
            key: "com.apple.springing.delay",
            value_type: ValueType::Float,
            constraint: float_range(0.0, 3.0, 0.1),
            description: "Spring-load delay",
            group: SettingGroup::ScrollWindow,
            mirror_domains: &[],
            requires_logout: false,
            help: "How long to hover before folder opens. Higher = slower",
        },
        // ── Group 6: Cursor & Accessibility ──
        SettingDef {
            id: "cursor_size",
            domain: UNIVERSAL_ACCESS,
            key: "mouseDriverCursorSize",
            value_type: ValueType::Float,
            constraint: float_range(1.0, 10.0, 0.25),
            description: "Cursor size",
            group: SettingGroup::CursorAccessibility,
            mirror_domains: &[],
            requires_logout: true,
            help: "Size of the mouse cursor. Higher = bigger",
        },
        SettingDef {
            id: "zoom_scroll_toggle",
            domain: UNIVERSAL_ACCESS,
            key: "closeViewScrollWheelToggle",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Scroll-wheel zoom",
            group: SettingGroup::CursorAccessibility,
            mirror_domains: &[],
            requires_logout: false,
            help: "Hold modifier key + scroll to zoom the screen",
        },
        SettingDef {
            id: "zoom_modifier_key",
            domain: UNIVERSAL_ACCESS,
            key: "closeViewScrollWheelModifiersInt",
            value_type: ValueType::Int,
            constraint: int_range(0, 1572864),
            description: "Zoom modifier key bitmask",
            group: SettingGroup::CursorAccessibility,
            mirror_domains: &[],
            requires_logout: false,
            help: "Which modifier key activates scroll zoom (macOS key bitmask)",
        },
        SettingDef {
            id: "reduce_motion",
            domain: UNIVERSAL_ACCESS,
            key: "reduceMotion",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Reduce motion",
            group: SettingGroup::CursorAccessibility,
            mirror_domains: &[],
            requires_logout: false,
            help: "Minimizes animations across macOS",
        },
        SettingDef {
            id: "shake_to_locate",
            domain: UNIVERSAL_ACCESS,
            key: "ShakeMouseCursorToLocate",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Shake cursor to locate",
            group: SettingGroup::CursorAccessibility,
            mirror_domains: &[],
            requires_logout: false,
            help: "Shake mouse rapidly to enlarge cursor temporarily",
        },
        // ── Group 7: Keyboard ──
        SettingDef {
            id: "key_repeat",
            domain: NSGLOBAL,
            key: "KeyRepeat",
            value_type: ValueType::Int,
            constraint: int_range(0, 120),
            description: "Key repeat rate (lower = faster)",
            group: SettingGroup::Keyboard,
            mirror_domains: &[],
            requires_logout: true,
            help: "Interval between repeated keystrokes. Lower = faster",
        },
        SettingDef {
            id: "initial_key_repeat",
            domain: NSGLOBAL,
            key: "InitialKeyRepeat",
            value_type: ValueType::Int,
            constraint: int_range(0, 120),
            description: "Delay until repeat (lower = shorter)",
            group: SettingGroup::Keyboard,
            mirror_domains: &[],
            requires_logout: true,
            help: "Delay before key starts repeating. Lower = shorter delay",
        },
        SettingDef {
            id: "press_and_hold",
            domain: NSGLOBAL,
            key: "ApplePressAndHoldEnabled",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Press-and-hold for accents (off = key repeat)",
            group: SettingGroup::Keyboard,
            mirror_domains: &[],
            requires_logout: false,
            help: "On: shows accent menu. Off: key repeats instead",
        },
        SettingDef {
            id: "fn_key_state",
            domain: NSGLOBAL,
            key: "com.apple.keyboard.fnState",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Fn key shows F1-F12",
            group: SettingGroup::Keyboard,
            mirror_domains: &[],
            requires_logout: false,
            help: "On: Fn keys are F1-F12. Off: media/special keys",
        },
        // ── Group 8: Text Input ──
        SettingDef {
            id: "auto_correct",
            domain: NSGLOBAL,
            key: "NSAutomaticSpellingCorrectionEnabled",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Auto-correct",
            group: SettingGroup::KeyboardText,
            mirror_domains: &[],
            requires_logout: false,
            help: "Automatically fixes spelling mistakes",
        },
        SettingDef {
            id: "auto_capitalize",
            domain: NSGLOBAL,
            key: "NSAutomaticCapitalizationEnabled",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Auto-capitalization",
            group: SettingGroup::KeyboardText,
            mirror_domains: &[],
            requires_logout: false,
            help: "Capitalizes first letter of sentences",
        },
        SettingDef {
            id: "smart_dashes",
            domain: NSGLOBAL,
            key: "NSAutomaticDashSubstitutionEnabled",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Smart dashes",
            group: SettingGroup::KeyboardText,
            mirror_domains: &[],
            requires_logout: false,
            help: "Converts double hyphens to em dashes",
        },
        SettingDef {
            id: "smart_quotes",
            domain: NSGLOBAL,
            key: "NSAutomaticQuoteSubstitutionEnabled",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Smart quotes",
            group: SettingGroup::KeyboardText,
            mirror_domains: &[],
            requires_logout: false,
            help: "Converts straight quotes to curly quotes",
        },
        SettingDef {
            id: "period_substitution",
            domain: NSGLOBAL,
            key: "NSAutomaticPeriodSubstitutionEnabled",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Double-space to period",
            group: SettingGroup::KeyboardText,
            mirror_domains: &[],
            requires_logout: false,
            help: "Typing two spaces inserts a period",
        },
        SettingDef {
            id: "auto_text_completion",
            domain: NSGLOBAL,
            key: "NSAutomaticTextCompletionEnabled",
            value_type: ValueType::Bool,
            constraint: Constraint::None,
            description: "Inline text completion",
            group: SettingGroup::KeyboardText,
            mirror_domains: &[],
            requires_logout: false,
            help: "Suggests words as you type",
        },
    ]
}
